#!/bin/bash 
#
#   Copyright
#
#       Copyright (C) 2013 Brian Duncan <brian@bingotree.com>
#
#   License
#
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#  Description
#
#       From patch file.
#       Show each hunk, prompt user to accept or not.
#       Apply accepted patch.

NAMESPACE='SPLITPATCH';
cat <<"PATCHSPLASH"
                          
                         .-"""""-.     
                        / __   __ \     
                       ; / _\ /_ \ ;   
                       |  / \ / \  |    
                      (,  \0/_\0/  ,)  
                       |   /   \   |  
                       | (_\___/_) |
                       .\ \ -.- / /.
                      {  \ `===' /  }
                     {    `.___.'    }
                      {             }
                       `"="="="="="`
   ___      _       _       _       _                      
  / _ \__ _| |_ ___| |__   /_\   __| | __ _ _ __ ___  ___  
 / /_)/ _` | __/ __| '_ \ //_\\ / _` |/ _` | '_ ` _ \/ __| 
/ ___/ (_| | || (__| | | /  _  \ (_| | (_| | | | | | \__ \ 
\/    \__,_|\__\___|_| |_\_/ \_/\__,_|\__,_|_| |_| |_|___/ 
PATCHSPLASH

read -sn 1 -p "Press any key to continue..."

settrap () {
trap "rm -f .${NAMESPACE}.*.patch*; exit 0;" INT
}

if [ $# -lt 1 ]; then
    echo "Usage: ${0##*/} <patchfile>";
    exit 1;
fi

INPUTFILE=$1

if [ $# -eq 2 ]; then
    LEVEL=$2
else
    LEVEL=1
fi

if [[ -r "$INPUTFILE" && -f "$INPUTFILE" ]]; then
    echo "Splitting $INPUTFILE into hunks."
else
    echo "Error: file '$INPUTFILE' cannot be found, is not a file or isn't readable.";
    exit 1;
fi
    
# Create temp location for hunks
splitpatch --hunks $INPUTFILE    
settrap
 
for patch in .${NAMESPACE}.*.patch*; do
    cat $patch
    echo -n 'Apply this patch? (y/n): '
    read prompt
    if [ "$prompt" = "y" ]; then
        patch -p${LEVEL} < $patch
    fi
done
rm -f .${NAMESPACE}.*.patch*
#Delete temp location for hunks
